#ifndef A8_ALGORITHMIC_TRADING_MODELS_INCLUDE_POINT_H_
#define A8_ALGORITHMIC_TRADING_MODELS_INCLUDE_POINT_H_

#include "libraries/math/utils/point.h"

#endif  // A8_ALGORITHMIC_TRADING_MODELS_INCLUDE_POINT_H_
